export default function Report({ habitData }) {
  const dates = Object.keys(habitData).filter(
    (k) => !k.startsWith("__")
  );

  let totalDays = dates.length;
  let morningCount = 0;
  let nightCount = 0;
  let flossCount = 0;
  let perfectDays = 0;

  dates.forEach((date) => {
    const d = habitData[date];
    if (!d) return;

    if (d.morning) morningCount++;
    if (d.night) nightCount++;
    if (d.floss) flossCount++;

    if (d.morning && d.night && d.floss) perfectDays++;
  });

  const percent = (n) =>
    totalDays ? Math.round((n / totalDays) * 100) : 0;

  const reportText = `
Smile Streak Dental Report

Tracked Days: ${totalDays}
Morning Brushing: ${percent(morningCount)}%
Night Brushing: ${percent(nightCount)}%
Interdental Cleaning: ${percent(flossCount)}%
Perfect Routine Days: ${percent(perfectDays)}%

Generated by Smile Streak
  `;

  const downloadReport = () => {
    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "smile-streak-report.txt";
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Dental Report</h1>

      <div className="bg-white rounded-2xl p-4 border space-y-2">
        <p>Tracked Days: {totalDays}</p>
        <p>Morning Brushing: {percent(morningCount)}%</p>
        <p>Night Brushing: {percent(nightCount)}%</p>
        <p>Interdental Cleaning: {percent(flossCount)}%</p>
        <p>Perfect Days: {percent(perfectDays)}%</p>
      </div>

      <button
        onClick={downloadReport}
        className="bg-blue-600 text-white px-4 py-3 rounded-xl font-semibold shadow"
      >
        Export for Dentist
      </button>
    </div>
  );
}
